%%
%% Autogenerated by Thrift
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(hadoopfs_types).

-include("hadoopfs_types.hrl").

-export([struct_info/1]).
%% struct thriftHandle

% -record(thriftHandle, {id}).

struct_info('thriftHandle') ->
  {struct, [{-1, i64}]}
;

%% struct pathname

% -record(pathname, {pathname}).

struct_info('pathname') ->
  {struct, [{-1, string}]}
;

%% struct fileStatus

% -record(fileStatus, {path, length, isdir, block_replication, blocksize, modification_time, permission, owner, group}).

struct_info('fileStatus') ->
  {struct, [{1, string},
  {2, i64},
  {3, bool},
  {4, i16},
  {5, i64},
  {6, i64},
  {7, string},
  {8, string},
  {9, string}]}
;

%% struct blockLocation

% -record(blockLocation, {hosts, names, offset, length}).

struct_info('blockLocation') ->
  {struct, [{1, {list, string}},
  {2, {list, string}},
  {3, i64},
  {4, i64}]}
;

%% struct malformedInputException

% -record(malformedInputException, {message}).

struct_info('malformedInputException') ->
  {struct, [{-1, string}]}
;

%% struct thriftIOException

% -record(thriftIOException, {message}).

struct_info('thriftIOException') ->
  {struct, [{-1, string}]}
;

struct_info('i am a dummy struct') -> undefined.
